import { PutObjectCommand } from '@aws-sdk/client-s3';
import { r2Client } from '../config/s3.js';

/**
 * PDF Generation Service
 * Generates PDF from news content and uploads to Cloudflare R2
 */

const getR2PublicBaseUrl = () => {
  const configuredUrl = process.env.R2_PUBLIC_URL || `${process.env.R2_BUCKET_NAME}.${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`;

  return configuredUrl.startsWith('http://') || configuredUrl.startsWith('https://')
    ? configuredUrl.replace(/\/$/, '')
    : `https://${configuredUrl.replace(/\/$/, '')}`;
};

/**
 * Generate HTML content for PDF
 */
export const generatePdfHtml = (newsArray, category, date) => {
  const newsHtml = newsArray
    .map(
      (news, index) => `
    <div style="page-break-inside: avoid; margin-bottom: 30px; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
      <h2 style="color: #DE277A; margin-bottom: 10px;">${index + 1}. ${news.title}</h2>
      <p style="color: #666; font-style: italic; margin-bottom: 15px;">${news.description}</p>
      <p>${news.content}</p>
      ${news.sourceUrl ? `<p style="margin-top: 10px;"><strong>Source:</strong> <a href="${news.sourceUrl}">${news.source}</a></p>` : ''}
      <p style="margin-top: 10px; color: #999; font-size: 12px;"><strong>Date:</strong> ${new Date(news.publishedDate || date).toLocaleDateString('en-IN')}</p>
    </div>
  `
    )
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${category} Updates - ${new Date(date).toLocaleDateString('en-IN')}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      color: #333;
      line-height: 1.6;
      margin: 0;
      padding: 20px;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #DE277A;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      color: #DE277A;
      margin: 0;
      font-size: 36px;
    }
    .header p {
      color: #666;
      margin: 5px 0 0 0;
    }
    .metadata {
      background-color: #f5f5f5;
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 20px;
      text-align: center;
    }
    .metadata p {
      margin: 5px 0;
      font-size: 14px;
      color: #666;
    }
    .news-item {
      page-break-inside: avoid;
      margin-bottom: 30px;
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 8px;
    }
    .news-item h2 {
      color: #DE277A;
      margin-bottom: 10px;
      margin-top: 0;
    }
    .news-item p {
      margin: 10px 0;
    }
    .source {
      color: #999;
      font-size: 12px;
      margin-top: 10px;
      font-style: italic;
    }
    .footer {
      margin-top: 50px;
      border-top: 1px solid #ddd;
      padding-top: 20px;
      text-align: center;
      color: #999;
      font-size: 12px;
    }
    a {
      color: #DE277A;
      text-decoration: none;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📰 ${category} Updates</h1>
    <p>GSC Intime Services Pvt. Ltd.</p>
  </div>
  
  <div class="metadata">
    <p><strong>Report Date:</strong> ${new Date(date).toLocaleDateString('en-IN')}</p>
    <p><strong>Total Articles:</strong> ${newsArray.length}</p>
    <p><strong>Category:</strong> ${category}</p>
  </div>

  <div class="content">
    ${newsHtml}
  </div>

  <div class="footer">
    <p>Generated by GSC Intime Services Private Limited</p>
    <p>© ${new Date().getFullYear()} All rights reserved. | www.gscintime.com</p>
  </div>
</body>
</html>
  `;
};

/**
 * Upload PDF to Cloudflare R2
 */
export const uploadPdfToS3 = async (pdfBuffer, fileName) => {
  try {
    const command = new PutObjectCommand({
      Bucket: process.env.R2_BUCKET_NAME,
      Key: `news-pdfs/${fileName}`,
      Body: pdfBuffer,
      ContentType: 'application/pdf',
    });

    await r2Client.send(command);

    const pdfUrl = `${getR2PublicBaseUrl()}/news-pdfs/${fileName}`;
    return pdfUrl;
  } catch (error) {
    console.error('Error uploading PDF to Cloudflare R2:', error);
    throw error;
  }
};

/**
 * Generate PDF file name with timestamp
 */
export const generatePdfFileName = (category, date = new Date()) => {
  const dateStr = date.toISOString().split('T')[0];
  const sanitizedCategory = category.replace(/\s+/g, '_').toLowerCase();
  return `${sanitizedCategory}_updates_${dateStr}.pdf`;
};

export default {
  generatePdfHtml,
  uploadPdfToS3,
  generatePdfFileName,
};
